'use strict';

/**
 * Prepare install: create runtime/logs dirs and generate service.generated.xml.
 * Run from repo root (release root), or pass base path as first argument.
 *
 *   node service/scripts/install.js
 *   node service/scripts/install.js D:\svc\current
 */

const fs = require('fs');
const path = require('path');

const scriptDir = __dirname;
const basePath = process.argv[2] || process.cwd();
const serviceDir = path.join(basePath, 'service');
const runtimeDir = path.join(serviceDir, 'runtime');
const logsDir = path.join(serviceDir, 'logs');
const serviceName = 'ParasceneProviderLocal';

// Create directories
for (const dir of [runtimeDir, logsDir]) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log('Created:', dir);
  }
}

// Generate WinSW config with actual paths
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by install.js - use with WinSW -->
<service>
  <id>ParasceneProviderLocal</id>
  <name>Parascene Provider Local</name>
  <description>Local AI provider service (supervisor + worker).</description>
  <executable>node</executable>
  <arguments>service/src/supervisor/index.js</arguments>
  <workingdirectory>${basePath}</workingdirectory>
  <logpath>${logsDir}</logpath>
  <log mode="roll-by-time">
    <pattern>yyyyMMdd</pattern>
  </log>
</service>
`;
const outPath = path.join(scriptDir, 'service.generated.xml');
fs.writeFileSync(outPath, xml, 'utf8');

console.log('Generated:', outPath);
console.log('Base path:', basePath);
console.log('Service directory:', serviceDir);
console.log('');
console.log('Next: use this config with WinSW (run as Administrator), e.g.:');
console.log('  WinSW.exe install -c "' + outPath + '"');
console.log('Then set recovery:');
console.log('  sc failure ' + serviceName + ' reset=86400 actions=restart/5000/restart/10000/restart/30000');
